---
- include_tasks: install.yml

- include_tasks: users.yml
  when: docker_pi_group_users|length > 0

- include_tasks: login.yml
  when:
    - docker_pi_hub_username|default('') != ''
    - docker_pi_hub_password|default('') != ''
